#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $POSTGRES_DB_AUTH;
    CREATE DATABASE $POSTGRES_DB_DOCUMENTS;
    CREATE DATABASE $POSTGRES_DB_ORCHESTRATOR;
    CREATE DATABASE $POSTGRES_DB_BILLING;
EOSQL
